### ISSUE TITLE
Lille Kat 2023:06 - Inflation

### ISSUE THREAD

**Issue by albe2669** [albe2669/kat-goes-off-the-deep-end#32]
Problem: Inflation
Problem URL: https://open.kattis.com/problems/inflation2
Contest URL: https://open.kattis.com/contests/p3d3fe/problems/inflation2

**Comment by avborup** [comment]
For future reference, we had a discussion while walking the Amarmino and realised that the problem requires the following functionality:

- Range queries (for sums, specifically)
- Dynamic range updates

Both of which can be implemented in $O(\log n)$ time with segment trees. The approach using binary trees during the contest was not far off!

**Comment by andreaswachs** [comment]
The 200iq insight into this problem is that you can skip any range updates and range queries by doing everything on hashmap with operations running in $O(1)$ time, with a sizable constant in front, though.

All that had to be done is maintaining some global variables (sum and total amount of prices) that are updated correctly. Only need to dive into hash map to adjust prices when one set of present dishes with a given price $x$ is changed to price $y$.
